spring.data.mongodb.uri=mongodb+srv://jadhavruchita27_db_user:ruchi@cluster0.ajdye1r.mongodb.net/visitorsdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=visitorsdb
server.port=${PORT:8080}
logging.level.org.springframework.data.mongodb=DEBUG

brevo.api.key=bskJ262DXef3err
brevo.sender.email=jadhavruchita27@gmail.com



# Server Upload Limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Increase the max size of JSON payloads
# (This prevents the 'book' request from being truncated)
server.tomcat.max-swallow-size=15MB
server.tomcat.max-http-form-post-size=15MB

