spring.data.mongodb.uri=mongodb+srv://jadhavruchita27_db_user:ruchi@cluster0.ajdye1r.mongodb.net/visitorsdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=visitorsdb
server.port=${PORT:8080}
logging.level.org.springframework.data.mongodb=DEBUG
spring.data.mongodb.repositories.enabled=true


# Web Push VAPID Keys (Ruchita's Real Keys)
vapid.public.key=BFPvV33eYXqMULaMcRCQp6CZpO_5ZP7PBaCkto-kfCKaQLeLFx3dD29EK2d0l5k5nJuH9OoGICBNnX-6LC7CIA8
vapid.private.key=h8OcB01sYf5qkBXXQ__sPnaxWoiJxNkIGt5y8VRZWs8
vapid.subject=mailto:jadhavruchita27@gmail.com
# Brevo Email Config


brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}




spring.mail.host=smtp.gmail.com
spring.mail.port=587




spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false

spring.mail.properties.mail.smtp.connectiontimeout=60000
spring.mail.properties.mail.smtp.timeout=60000
spring.mail.properties.mail.smtp.writetimeout=60000

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
spring.mail.properties.mail.debug=true

# Server Upload Limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Increase the max size of JSON payloads
# (This prevents the 'book' request from being truncated)
server.tomcat.max-swallow-size=15MB
server.tomcat.max-http-form-post-size=15MB

